---
title: Final Review"
author: 'Output'
date: "May 7, 2018"
output: html_document
---
  
  <style type="text/css">
  .table {
    
    width: 80%;
    margin-left:10%; 
    margin-right:10%;
  }
</style>
  
```{r,setup, cache=TRUE, echo=F}
## numbers >= 10^5 will be denoted in scientific notation,
## and rounded to 2 digits
options(scipen = 3, digits = 4)
suppressMessages( require(car))

```

```{r, echo=FALSE}
library(foreign)
fhs <- read.dta("fhs.dta")
```

#Output



## Logistic Model Output




```{r, echo=FALSE}
mod1 <- glm(hyperten ~ age1, family=binomial, data=fhs)
mod2 <- glm(hyperten ~ cursmoke1, family=binomial, data=fhs)
mod3 <- glm(hyperten ~ cigpday1, family=binomial, data=fhs)
mod4 <- glm(hyperten ~ bmi1, family=binomial, data=fhs)
mod5 <- glm(hyperten~ diabetes1, family=binomial, data=fhs)
mod6 <- glm(hyperten ~ bpmeds1, family=binomial, data=fhs)
mod7 <- glm(hyperten ~ heartrte1, family=binomial, data=fhs)
mod8 <- glm(hyperten ~ prevmi1, family=binomial, data=fhs)
mod9 <- glm(hyperten~sysbp1, family=binomial, data=fhs)
```

```{r}

# Model 1  - Hypertension = beta0 + beta1*age
summary(mod1)
```


\newpage

```{r}
#Model 2 - Hypertension = beta0 + beta1* (current smoker)
summary(mod2)
```

```{r}

#Model 3 - Hypertension = beta0 + beta1*(cigs per day)
summary(mod3)
```


\newpage 

```{r}
#Model 4 - Hyptertension = beta0 + beta1*(bmi)
summary(mod4)
```

```{r}
#Model 5 - Hypertension = beta0 + beta1*(diabetes)
summary(mod5)

```

\newpage

```{r}
#model 6 - Hypertension = beta0 + beta1*(Blood Pressure Meds)
summary(mod6)
```

```{r}
#Model 7 - Hypertension = beta0 + beta1*(Heart Rate)
summary(mod7)
```


\newpage 
```{r}
#Model 8 - Hypertension = beta0 + beta1*(Heart Attacks)
summary(mod8)
```

```{r}
#Model 9 - Hypertension = beta0 + beta1*(Systolic Blood Pressure)
summary(mod9)
```

\newpage

```{r,  echo=FALSE}

keep <- c("hyperten"  , "age1" ,  "cursmoke1",   "cigpday1",   "bmi1" , "diabetes1" ,  "bpmeds1",   "heartrte1",  "prevmi1" ,  "sysbp1", "timehyp" )
fhs1 <- fhs[, keep]
fhs1 <- fhs1[complete.cases(fhs1),]

#library(MASS)
#fit <- glm(hyperten ~ age1 + cursmoke1 + cigpday1 + bmi1 + diabetes1 + bpmeds1 + heartrte1+ prevmi1 + sysbp1 , family=binomial, data=fhs1)
#step <- stepAIC(fit, direction = "both")
```




```{r, echo=FALSE}
mod10 <- glm(hyperten ~ age1 + cursmoke1 + cigpday1 + bmi1 + diabetes1 + bpmeds1 + heartrte1+ prevmi1 + sysbp1 , family=binomial, data=fhs1)
mod11 <- glm(hyperten ~ age1 + cursmoke1+ bmi1  + bpmeds1 + heartrte1+ prevmi1 + sysbp1 , family=binomial, data=fhs1)
mod12 <- glm(hyperten ~ cursmoke1 + bmi1 +  bpmeds1 , family=binomial, data=fhs1)
mod13 <- glm(hyperten ~ cursmoke1 + bmi1 + bpmeds1 + sysbp1 , family=binomial, data=fhs1)

```

```{r}
# Model 10 - Hypertension = beta0 + beta1*(age) + beta2*(current smoker) + beta3*(cigs per day) 
#+ beta4*(bmi) + beta5*(diabetes) + beta6*(blood pressure meds)  + beta7*(Heart Rate)
#+ beta8*(Heart Attacks)   + beta9*(Systolic Blood Pressure)
summary(mod10)
```


\newpage

```{r}
# Model 11 - Hypertension = beta0 + beta1*(age) + beta2*(current smoker)  + beta3*(bmi) 
#+ beta4*(blood pressure meds) + beta5*(Heart Rate)  + beta6*(Heart Attacks)
#+ beta7*(Systolic Blood Pressure)
summary(mod11)
```

\newpage

```{r}
# Model 12 - Hypertension = beta0 + beta1*(current smoker) + beta2*(bmi) +beta3*(blood pressure meds) 
summary(mod12)
```

\newpage

```{r}

# Model 13 - Hypertension = beta0 + beta1*(current smoker) + beta2*(bmi) +beta3*(blood pressure meds) 
#+ beta4*(Systolic Blood Pressure)
summary(mod13)
```



```{r, echo=FALSE, results='hide' }

suppressMessages(library(ggplot2))
suppressMessages(library(ROCR))

prob1 <- predict(mod10)
pred1 <- prediction(prob1, fhs1$hyperten)
perf1 <- performance(pred1, "tpr", "fpr")
# I know, the following code is bizarre. Just go with it.
auc1 <- performance(pred1, measure = "auc")
auc1 <- auc1@y.values[[1]]

roc.data1 <- data.frame(fpr=unlist(perf1@x.values),
                       tpr=unlist(perf1@y.values),
                       model="GLM")
ggplot(roc.data1, aes(x=fpr, ymin=0, ymax=tpr)) +
    geom_ribbon(alpha=0.2) + geom_abline(intercept = 0, slope = 1, colour = "gray")+
    geom_line(aes(y=tpr)) +
    ggtitle(paste0("Model 10 ROC Curve w/ AUC=", auc1))


prob2 <- predict(mod11)
pred2 <- prediction(prob2, fhs1$hyperten)
perf2 <- performance(pred2, "tpr", "fpr")
# I know, the following code is bizarre. Just go with it.
auc2 <- performance(pred2, measure = "auc")
auc2 <- auc2@y.values[[1]]

roc.data2 <- data.frame(fpr=unlist(perf2@x.values),
                       tpr=unlist(perf2@y.values),
                       model="GLM")
ggplot(roc.data2, aes(x=fpr, ymin=0, ymax=tpr)) +
    geom_ribbon(alpha=0.2) + geom_abline(intercept = 0, slope = 1, colour = "gray")+
    geom_line(aes(y=tpr)) +
    ggtitle(paste0("Model 11 ROC Curve w/ AUC=", auc2))


prob3 <- predict(mod12)
pred3 <- prediction(prob3, fhs1$hyperten)
perf3 <- performance(pred3, "tpr", "fpr")
# I know, the following code is bizarre. Just go with it.
auc3 <- performance(pred3, measure = "auc")
auc3 <- auc3@y.values[[1]]

roc.data3 <- data.frame(fpr=unlist(perf3@x.values),
                       tpr=unlist(perf3@y.values),
                       model="GLM")
ggplot(roc.data3, aes(x=fpr, ymin=0, ymax=tpr)) +
    geom_ribbon(alpha=0.2) + geom_abline(intercept = 0, slope = 1, colour = "gray")+
    geom_line(aes(y=tpr)) +
    ggtitle(paste0("Model 12 ROC Curve w/ AUC=", auc3))



prob4 <- predict(mod13)
pred4 <- prediction(prob4, fhs1$hyperten)
perf4 <- performance(pred4, "tpr", "fpr")
# I know, the following code is bizarre. Just go with it.
auc4 <- performance(pred4, measure = "auc")
auc4 <- auc4@y.values[[1]]

roc.data4 <- data.frame(fpr=unlist(perf4@x.values),
                       tpr=unlist(perf4@y.values),
                       model="GLM")
ggplot(roc.data4, aes(x=fpr, ymin=0, ymax=tpr)) +
    geom_ribbon(alpha=0.2) + geom_abline(intercept = 0, slope = 1, colour = "gray")+
    geom_line(aes(y=tpr)) +
    ggtitle(paste0("Model 13 ROC Curve w/ AUC=", auc4))
```




```{r}
#LRT: Model 10 vs Model 11
anova(mod10, mod11, test ="Chisq" )

#LRT: Model 10 vs Model 12
anova(mod10, mod12, test ="Chisq")

#LRT: Model 10 vs Model 13
anova(mod10, mod13, test ="Chisq")

#LRT: Model 11 vs Model 12
anova(mod11, mod12, test ="Chisq")

#LRT: Model 11 vs Model 13
anova(mod11, mod13, test ="Chisq")

#LRT: Model 12 vs Model 13
anova(mod12, mod13, test ="Chisq")
```


\newpage

## Surival Model Output





```{R, echo=FALSE}
library(survival)
surv <- Surv(as.numeric(fhs1$timehyp), as.numeric(fhs1$hyperten))
mod14 <- coxph(surv ~  age1 + cursmoke1 + cigpday1 + bmi1 + diabetes1 + bpmeds1 + heartrte1+ prevmi1 + sysbp1, data=fhs1)
mod14a <-  coxph(surv ~  age1 + cursmoke1 + cigpday1 + bmi1 + diabetes1 + bpmeds1 + heartrte1+ prevmi1 + strata(sysbp1), data=fhs1)
mod15 <- coxph(surv ~ age1 + cursmoke1+ bmi1  + bpmeds1 + heartrte1+ prevmi1 + sysbp1 , data=fhs1)
mod15a <- coxph(surv ~ age1 + cursmoke1+ bmi1  + bpmeds1 + heartrte1+ prevmi1 + strata(sysbp1) , data=fhs1)
mod16 <- coxph(surv ~ cursmoke1 + bmi1 +  bpmeds1 , data=fhs1)
mod16a <- coxph(surv ~ cursmoke1 + strata(bmi1) +  bpmeds1 , data=fhs1)
mod17 <- coxph(surv ~ cursmoke1 + bmi1 + bpmeds1 + sysbp1 ,  data=fhs1)
mod17a <- coxph(surv ~ cursmoke1 + bmi1 + bpmeds1 + strata(sysbp1) ,  data=fhs1) 

```



```{r}
#Cox PH
# Model 14 - Hypertension = beta0 + beta1*(age) + beta2*(current smoker) + beta3*(cigs per day) + 
#beta4*(bmi) + beta5*(diabetes) + beta6*(blood pressure meds)
# + beta7*(Heart Rate) + beta8*(Heart Attacks) + beta9*(Systolic Blood Pressure)
summary(mod14)
```

\newpage

```{r}
cox.zph(mod14)
```


```{r}
#Cox PH
# Model 14a - Hypertension = beta0 + beta1*(age) + beta2*(current smoker) + beta3*(cigs per day)
# + beta4*(bmi)  + beta5*(diabetes) + beta6*(blood pressure meds) 
# + beta7*(Heart Rate) + beta8*(Heart Attacks)  
#adjusted for systolic blood pressure with strata command
summary(mod14a)
```



```{r}
cox.zph(mod14a)
```


```{r}
#Cox PH
# Model 15 - Hypertension = beta0 + beta1*(age) + beta2*(current smoker)  + beta3*(bmi) 
#+ beta4*(blood pressure meds)  + beta5*(Heart Rate)  + beta6*(Heart Attacks)
#+ beta7*(Systolic Blood Pressure)
summary(mod15)
cox.zph(mod15)
```


```{r}
#Cox PH
# Model 15a - Hypertension = beta0 + beta1*(age) + beta2*(current smoker)  + beta3*(bmi) 
#+ beta4*(blood pressure meds)  + beta5*(Heart Rate)  + beta6*(Heart Attacks)
#    adjust for Systolic Blood Pressure with strata command
summary(mod15a)
```

\newpage 

```{r}
cox.zph(mod15a)
```

```{r}
#Cox PH
# Model 16 - Hypertension = beta0 + beta1*(current smoker) + beta2*(bmi) +beta3*(blood pressure meds) 
summary(mod16)
cox.zph(mod16)
```

\newpage

```{r}
#Cox PH
# Model 16a - Hypertension = beta0 + beta1*(current smoker)  +beta2*(blood pressure meds) 
# Adjusted for BMI with strata command
summary(mod16a)
cox.zph(mod16a)
```

\newpage

```{r}
#Cox PH
# Model 17 - Hypertension = beta0 + beta1*(current smoker) + beta2*(bmi) +beta3*(blood pressure meds)
#+ beta4*(Systolic Blood Pressure)
summary(mod17)
cox.zph(mod17)
```

\newpage

```{r}
#Cox PH
# Model 17a - Hypertension = beta0 + beta1*(current smoker) + beta2*(bmi) +beta3*(blood pressure meds)
# ajdustled for Systolic Blood Pressure with the strata command
summary(mod17a)
cox.zph(mod17a)
```


```{r}
#LRT: Model 14 vs Model 15
anova(mod14a, mod15a)
```

\newpage 

```{r}
#LRT: Model 14 vs Model 16
anova(mod14a, mod16a)

#LRT: Model 14 vs Model 17
anova(mod14a, mod17a)

#LRT: Model 15 vs Model 16
anova(mod15a, mod16a)

#LRT: Model 15 vs Model 17
anova(mod15a, mod17a)

#LRT: Model 16 vs Model 17
anova(mod16a, mod17a)
```
