seeds = read.table("seeds.txt", header=T)
seeds = read.table("http://www.stat.duke.edu/courses/Fall08/sta290/datasets/seeds.txt", header=T)
summary(seeds)
par(mfrow=c(1,1))
plot(seeds)
attach(seeds)
table(PLOT, SUBPLT)
seeds.glm0 = glm(SURV ~ 1, data=seeds, family=binomial)
seeds.glm1 = glm(SURV ~  CAGE + LIGHT, data=seeds, family=binomial)
seeds.glm2 = glm(SURV ~  CAGE + log(LIGHT), data=seeds, family=binomial)
par(mfrow=c(2,2))
plot(seeds.glm1, ask=F)
summary(seeds.glm1)
anova(seeds.glm1, test="Chi")
seeds.glm3 = glm(SURV ~  SPECIES + CAGE + log(LIGHT) + factor(LITTER), data=seeds, family=binomial)
summary(seeds.glm3)
anova(seeds.glm3, test="Chi")
seeds.glm4 = glm(SURV ~  SPECIES*CAGE*log(LIGHT)*factor(LITTER), data=seeds, family=binomial)
seeds.glm4 = glm(SURV ~  SPECIES*CAGE*log(LIGHT)*factor(LITTER), data=seeds, family=binomial)

anova(seeds.glm4, test="Chi")
