---
title: "Longitudinal Data Analysis"
author: "Adam J Sullivan, PhD"
date: "04/11/2018"
output:
   ioslides_presentation: 
    widescreen: true
notes: ''
link: yes
slides: yes
layout: page
css:  "C:/Users/adam_/Dropbox (Personal)/Brown/Teaching/Brown Courses/PHP2511/Spring 2018/website/php-1511-2511.github.io/Notes/slides.css"
---

```{r setup, include = FALSE, cache = FALSE}
library(knitr)
opts_chunk$set(error = TRUE)
opts_chunk$set(warning=FALSE)
opts_chunk$set(message=FALSE)
opts_chunk$set(results="hold")
opts_chunk$set(cache=T)
opts_chunk$set(  tidy=F,size="small")
opts_chunk$set(tidy.opts=list(width.cutoff=60))
options(digits = 3, scipen = 3)
```


# Longitudinal Data Analysis

## Cross-Sectional Studies

- Up until this point we have focused on what we call Cross-sectional data. 
- Cross-sectional data is data that is contained at a single time point. 
- This is basically a snapshot in time so there is no way to measure how things change over the course of time. 
- These are affordable to run and can measure many things at the same time. 

## Longitudinal Studies

- Longitudinal studies observe a group of subjects over a certain period of time.  
- This means that there are at least 2 time points of measuring variables. 
- Longitudinal studies allow you to observe how a treatment impacts things. 


## Longitudinal vs Cross-sectional

- Cross-sectional are quicker and cheaper to run. 
- Many times cross-sectional studies are run first to test for associations prior to a longitudinal. 
- Longitudinal allows for causality to be explored. 
- Longitudinal data is more difficult to analyze. 

## What makes Longitudinal Data Different? 

- **Correlation**
    - In cross-sectional studies we assume that data points are independent of each other. 
    - We cannot do this in longitudinal because each subjects data are completely dependent. 
    - If a subject has high cholesterol at one occasion they are likely to be high at the next occasion. 
    
    
## What makes Longitudinal Data Different? 

- **Variability**

    

